import { StyleSheet } from "react-native";
const styleUserPage = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ebe7e0',
    },
    boxHeader: {
        marginTop: 25,
        marginHorizontal: 20,
        width: '90%',
        height: '10%',
        backgroundColor: '#44749d',
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
    },
    boxTextHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 20,
    },
    boxIconHeader: {
        //flexDirection: 'row',
        //alignItems: 'center',
        marginRight: 20,
    },
    boxData: {
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        //marginTop: 10,
        width: '90%',
        height: '78%',
        backgroundColor: '#c6d4e1',
        marginHorizontal: 20,
        flexDirection: 'column',
        justifyContent: 'space-between',
        paddingVertical: 4,
        alignItems: 'center'
    },
    boxDataItem: {
        marginTop: 15,
        width: '90%',
        height: "20%",
        backgroundColor: '#44749d',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        alignItems: 'center',
    },
    boxDataItem2: {
        marginTop: 10,
        fontSize: 20,
        width: "90%",
        height: "40%",
        backgroundColor: '#ebe8e8',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',

    },
    boxDelete: {
        marginVertical: 30,
        width: '90%',
        height: "10%",
        backgroundColor: '#f22b56',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        justifyContent: 'center',
    },
    boxEditPassword: {
        marginTop: 10,
        width: '90%',
        height: "10%",
        backgroundColor: '#4d8f81',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        justifyContent: 'center',
    },
    titleHeader: {
        fontSize: 30,
        color: 'white',
        fontWeight: 'bold',
    },
    footer: {
        flexGrow: 1,
        justifyContent: 'flex-end',
    },
    icon: {
        width: 40, // Ajusta el ancho de la imagen según tus necesidades
        height: 40,
    },
    textPrimary: {
        marginTop: 10,
        fontSize: 25,
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    textSecundary: {
        fontSize: 20,
        color: '#44749d',
        fontWeight: 'bold',
        textAlign: 'center',
        justifyContent: 'center',
    },
    textBottom: {
        fontSize: 20,
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
        justifyContent: 'center',
    },

});
export default styleUserPage;