import { StyleSheet } from "react-native";

const styleDataTeamPage = StyleSheet.create({
    boxMembers: {
        marginTop: 25,
        marginHorizontal: 20,
        width: '90%',
        height: '40%',
        backgroundColor: '#44749d',
        alignItems: 'center',
        flexDirection: 'column',
        justifyContent: 'center',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        padding: 10,
    },
    boxDataMembers: {
        marginTop: 10,
        //marginHorizontal: 20,
        width: '90%',
        height: '80%',
        backgroundColor: '#ebe8e8',
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
    },
    boxBottom: {
        width: '90%',
        height: "30%",
        backgroundColor: '#d9bf56',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        justifyContent: 'center',
        margin: 5,
    },
    containerBottom: {
        marginTop: 5,
        width: '100%',
        height: '30%',
        //backgroundColor: '#44749d',
        alignItems: 'center',
        flexDirection: 'column',
        justifyContent: 'center',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        //padding: 10,
    },
});
export default styleDataTeamPage;