import { StyleSheet } from 'react-native';


const styleBox = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    containerPage: {
        flex: 1,
        backgroundColor: '#0c04b6',
    },
    header: {
        backgroundColor: '#0c04b6',
        height: 120,
        marginHorizontal: 15,
        //marginTop: 25,
        borderRadius: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
    },
    headerEdit: {
        //backgroundColor: '#0c04b6',
        //height: 80,
        //marginHorizontal: 15,
        //marginTop: 25,
        borderRadius: 20,
        //flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    iconHeader: {
        width: 60,
        height: 60,
        backgroundColor: 'white',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    dataContainer: {
        paddingTop: 5,
        paddingHorizontal: 20,
        height: 290,
        //borderRadius: 20,
        //backgroundColor: 'orange',

    },
    dataTitle: {
        width: '100%',
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',

        //paddingHorizontal: 20,
        //backgroundColor: 'black',
    },
    dataBox: {
        width: 320,
        height: 245,
        backgroundColor: 'white',
        borderRadius: 30,
        marginTop: 10,
        padding: 15,
        marginHorizontal: 10,
        shadowColor: 'black',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5, // Only for Android
    },
    line: {
        width: '100%',
        height: 2,
        backgroundColor: '#cfcfcf',
        margin: 4,
    },
    line2: {
        width: '100%',
        height: 2,
        backgroundColor: '#cfcfcf',
        marginVertical: 10,
    },
    codeBoton: {
        marginTop: 10,
        width: '100%',
        height: 40,
        backgroundColor: '#cfcfcf',
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    infoBoton: {
        marginTop: 10,
        paddingHorizontal: 20,
        width: '100%',
        height: 60,
        backgroundColor: 'white',
        borderRadius: 5,
        alignItems: 'center',
        flexDirection: 'row',
        elevation: 5, // Only for Android
    },
    listBoton: {
        marginTop: 10,
        width: '100%',
        height: 110,
        backgroundColor: 'white',
        borderRadius: 5,
        alignItems: 'center',
        flexDirection: 'row',
        elevation: 5, // Only for Android
        marginBottom: 10,
    },
    goBoton: {
        marginTop: 10,
        width: '30%',
        height: 40,
        backgroundColor: '#0c04b6',
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerPage: {
        //backgroundColor: '#0c04b6',
        //height: 80,
        //marginHorizontal: 15,
        marginTop: 25,
        borderRadius: 20,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        padding: 20,
    },
    contentPage: {
        height: 710,
        backgroundColor: '#f5f5f5',
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        padding: 20,
        //justifyContent: 'center',
        //alignItems: 'center',
    },
    dataInfo: {
        width: '100%',
        height: 50,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
        shadowColor: 'black',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5, // Only for Android
        backgroundColor: 'white',
    },
    botonEdit: {
        width: '100%',
        height: 50,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 30,
        shadowColor: 'black',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5, // Only for Android
        backgroundColor: '#ffc107',
    },
    botonDelete: {
        width: '100%',
        height: 50,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 30,
        //shadowColor: 'black',
        //shadowOffset: { width: 0, height: 2 },
        //shadowOpacity: 0.25,
        //shadowRadius: 4,
        //elevation: 5, // Only for Android
        backgroundColor: '#da1a29',
    },
    botonConfirm: {
        width: '100%',
        height: 50,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 30,
        backgroundColor: '#0c04b6',
    },
    option: {
        width: '49%',
        height: 50,
        backgroundColor: 'white',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    dataList: {
        width: '100%',
        height: 500,
        //backgroundColor: 'white',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,

        //elevation: 5, // Only for Android
    },
    listMember: {
        marginTop: 5,
        width: '100%',
        height: 200,
        alignItems: 'center',
        flexDirection: 'row',
    },
    infoDropdown: {
        marginTop: 10,
        width: '100%',
        height: 60,
        backgroundColor: 'white',
        borderRadius: 5,
        paddingHorizontal: 20,
        justifyContent: 'center',
        elevation: 5, // Only for Android
    },

});
export default styleBox;