import { StyleSheet } from "react-native";

const styleProjectUser = StyleSheet.create({
    boxContainer: {
        marginTop: 30,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        width: '90%',
        height: '93%',
        backgroundColor: '#44749d',
        marginHorizontal: 20,
        flexDirection: 'column',
        justifyContent: 'center',
        paddingVertical: 4,
        alignItems: 'center'
    },
    boxContainer2: {
        marginTop: 5,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        width: '90%',
        height: '73%',
        backgroundColor: '#44749d',
        marginHorizontal: 20,
        flexDirection: 'column',
        justifyContent: 'center',
        paddingVertical: 4,
        alignItems: 'center'
    },
    textTitle: {
        marginTop: 10,
        fontSize: 30,
        color: '#ebe8e8',
        fontWeight: 'bold',
        textAlign: 'center',
        justifyContent: 'center',
        marginHorizontal: 10,
    },
    textTitle2: {
        marginTop: 10,
        fontSize: 30,
        color: '#44749d',
        fontWeight: 'bold',
        textAlign: 'center',
        justifyContent: 'center',
        marginHorizontal: 10,
    },
    boxList: {
        marginTop: 20,
        marginHorizontal: 18,
        fontSize: 20,
        width: '90%',
        height: 230,
        backgroundColor: '#ebe8e8',
        borderRadius: 10,
        //justifyContent: 'space-between',
        //alignItems: 'center',
        //flexDirection: 'row',
    },
    boxBottom: {
        marginVertical: 30,
        marginHorizontal: 18,
        width: '90%',
        height: "8%",
        backgroundColor: '#d9bf56',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        justifyContent: 'center',
    },
    boxItemList: {
        marginTop: 5,
        paddingHorizontal: 15,
        marginHorizontal: 10,
        fontSize: 20,
        width: '90%',
        height: 50,
        backgroundColor: 'green',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexDirection: 'row-reverse',
    },
    boxHeader: {
        padding: 10,
        marginTop: 35,
        marginHorizontal: 20,
        width: '90%',
        height: '10%',
        backgroundColor: '#44749d',
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
    },

});
export default styleProjectUser;