import { StyleSheet } from "react-native";

const styleTeamPage = StyleSheet.create({
    boxDataItem: {
        //marginTop: 15,
        width: '90%',
        height: "30%",
        backgroundColor: '#44749d',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        alignItems: 'center',
    },
    boxDataItem2: {
        marginTop: 20,
        fontSize: 30,
        width: "90%",
        height: "40%",
        backgroundColor: '#ebe8e8',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    textBox1: {
        marginTop: 10,
        fontSize: 30,
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    boxBottom1: {
        marginVertical: 40,
        width: '90%',
        height: "20%",
        backgroundColor: '#f22b56',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        justifyContent: 'center',
    },
    boxBottom2: {
        marginVertical: 5,
        width: '90%',
        height: "20%",
        backgroundColor: '#d9bf56',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        justifyContent: 'center',
    },
});
export default styleTeamPage;