import { StyleSheet } from "react-native";

const styleAddPage = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ebe7e0',
    },
    footer: {
        flexGrow: 1,
        justifyContent: 'flex-end',
    },
    boxHeader: {
        marginTop: 25,
        marginHorizontal: 20,
        width: '90%',
        height: '10%',
        backgroundColor: '#44749d',
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
    },
    titleHeader: {
        fontSize: 30,
        color: 'white',
        fontWeight: 'bold',
    },
    boxContainer: {
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        //marginTop: 10,
        width: '90%',
        height: '78%',
        //backgroundColor: '#c6d4e1',
        marginHorizontal: 20,
        flexDirection: 'column',
        justifyContent: 'center',
        paddingVertical: 4,
        alignItems: 'center'
    },
    boxAddTeam: {
        marginTop: 20,
        width: '90%',
        height: "28%",
        backgroundColor: '#d9bf56',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
    },
    boxAddProyect: {
        marginTop: 20,
        width: '90%',
        height: "28%",
        backgroundColor: '#f9774b',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
    },
    boxAddTask: {
        marginTop: 20,
        width: '90%',
        height: "28%",
        backgroundColor: '#f22b56',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
    },
    boxTextHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 20,
    },
    boxIconHeader: {
        width: 50,
        height: 50,
        //flexDirection: 'row',
        //alignItems: 'center',
        marginRight: 20,
        marginHorizontal: 20
    },
});
export default styleAddPage;